<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * ArticleSubTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleSubTypeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function getFindAllQB(){
        $qb = $this->createQueryBuilder('t')
        ->select('t')
        ->orderBy('t.label','ASC');
        
        return $qb;
    }
    
    /**
     * @return array
     */
    public function findAll(){
        return $this->getFindAllQB()->getQuery()->getResult();
    }
      
}
