<?php

namespace AppBundle\Repository;

/**
 * articleLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
