<?php

namespace AppBundle\Repository;

/**
 * DateTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
