<?php

namespace AppBundle\Repository;

/**
 * EvolutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvolutionRepository extends \Doctrine\ORM\EntityRepository
{
}
