<?php

namespace AppBundle\Repository;

/**
 * LifeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LifeRepository extends \Doctrine\ORM\EntityRepository
{
}
