<?php

namespace AppBundle\Repository;

/**
 * ResourceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
