<?php

namespace App\Repository;

use App\Entity\ArticleLink;
use Doctrine\ORM\QueryBuilder;

/**
 * articleLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleLinkRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @param integer $parentId
     * @param integer $childId
     * @param int $limit
     * @return ArticleLink|NULL
     */
    public function findByParentChild($parentId,$childId,?int $limit)
    {
        $qb = $this->createQueryBuilder('l')
        ->where('l.parentArticle = :parent')
        ->andWhere('l.childArticle = :child');
        
        return $qb->getQuery()
        ->getOneOrNullResult();
    }

    /**
     * @param QueryBuilder $qb
     * @param int $parentId
     * @param int $limit
     * @return QueryBuilder
     */
    public function filterByParent_id(QueryBuilder $qb,int $parentId,?int $limit){
        return $qb
            ->join('o.parent','p')
            ->where('p.id = :parentId')
            ->setParameter('parentId',$parentId);
    }
    
    
    
}
