<?php
namespace App\Repository;

use App\Entity\ArticleStatus;
use App\Entity\ArticleType;
use App\Entity\User;
use App\Helper\DateHelper;
use App\Mapper\AutoMapper;
use App\Util\HDate;
use App\Util\SearchBag;
use Doctrine\ORM\EntityRepository;
use App\Entity\Article;
use App\Factory\ArticleDTOFactory;
use App\Factory\ArticleCollectionDTOFactory;
use App\DTO\ArticleModalDTO;
use App\DTO\ArticleMainDTO;
use App\DTO\ArticleCollectionDTO;
use App\Helper\StaticHelper;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    private $keywordIndex =[];


    /**
     * @param QueryBuilder $qb
     * @param ArticleType|null $type
     * @return QueryBuilder
     */
    public function filterByType(QueryBuilder $qb,?ArticleType $type){
        if($type === null) return $qb;
        return $qb->andWhere('o.type = :type')
            ->setParameter('type',$type);
    }

    /**
     * @param QueryBuilder $qb
     * @param $publicOnly
     * @return QueryBuilder
     */
    public function filterByPublicOnly(QueryBuilder $qb,$publicOnly){
        return $qb->andWhere('o.status = :status')
            ->setParameter('status',ArticleStatus::PUBLIC);
    }

    /**
     * @param QueryBuilder $qb
     * @param string $order
     * @return QueryBuilder
     */
    public function sortByTitle(QueryBuilder $qb,string $order){
        return $qb->orderBy('o.title',$order);
    }

    /**
     * do nothing since the sort is already made by relevance inside the filterByKeyword function
     * @param QueryBuilder $qb
     * @param string $order
     * @return QueryBuilder
     */
    public function sortByKeyword(QueryBuilder $qb,string $order){
        return $qb;
    }

    /**
     * @param QueryBuilder $qb
     * @param string|null $keyword
     * @param $options
     * @return QueryBuilder
     */
    public function filterByKeyword(QueryBuilder $qb,?string $keyword,$options){
        if($keyword === null || $keyword === "") return $qb;
        /*$keywordPieces = explode(':',$keyword);
        $conditions = [];
        foreach ($keywordPieces as $piece){
            $piece = "'%" . strtolower(trim($piece)) . "%'";
            $conditions[] = $qb->expr()->orX(
                $qb->expr()->like($qb->expr()->lower('o.title'),$piece),
                $qb->expr()->like($qb->expr()->lower('o.abstract'),$piece)
            );
        }
        $condition = $qb->expr()->orX()->addMultiple($conditions);*/

        $limit = 20;
        $publicOnly = 'false';
        $userId = null;

        if ($options!==null && array_key_exists('searchBag',$options)){
            $searchBag = $options['searchBag'];
            /** @var SearchBag $searchBag */
            if($searchBag !== null){
                $limit=$searchBag->getLimit();
                $publicOnly = array_key_exists('publicOnly',(array)($searchBag->getSearch()))?'true':'false';
            }
        }
        if ($options!==null && array_key_exists('user',$options)) {
            /** @var User $user */
            $user = $options['user'];
            $userId = $user?$user->getId():null;
        }

        $getIdByRelevanceQuery = "select * from get_article_ids_by_relevance(?,?,?,?);";
        $statement = $this->getEntityManager()->getConnection()->prepare($getIdByRelevanceQuery);
        $statement->execute([$keyword,$limit,$userId,$publicOnly]);
        $idsAndRelevance = $statement->fetchAll();
        $idsByRelevance = [];

        foreach($idsAndRelevance as $record){
            $idsByRelevance[$record['id']] = $record['relevance'];
        }

        $qb->andWhere($qb->expr()->in('o.id',array_keys($idsByRelevance)));

        $this->keywordIndex[$keyword] = $idsByRelevance;


        return $qb;
    }

    public function postProcessResultByKeyword($result,$keyword){

        if(array_key_exists($keyword,$this->keywordIndex)){
            $index = $this->keywordIndex[$keyword];
            $truc = 'la';

            usort($result,function($a,$b) use ($index) {
                return $index[intval($a->getId())] >= $index[intval($b->getId())]?-1:1;

            });
        }

        $truc = 'la';

        return $result;
    }

    /**
     * @param QueryBuilder $qb
     * @param string $order
     * @return QueryBuilder
     */
    public function sortByType_label(QueryBuilder $qb,string $order){
        return $qb->join('o.type','t')
        ->orderBy('t.label',$order);
    }

    /**
     * @param QueryBuilder $qb
     * @param HDate|null $hDate
     * @return QueryBuilder
     */
    public function filterByBeginHDate(QueryBuilder $qb,?HDate $hDate,$options){
        if($hDate === null) return $qb;
        return $qb->andWhere('(o.endDateType IS NULL OR o.endDateMaxIndex >= :beginDateMinIndex)')
            ->setParameter('beginDateMinIndex', DateHelper::dateToIndex($hDate->getBeginDate()));
    }

    /**
     * @param QueryBuilder $qb
     * @param string $order
     * @return QueryBuilder
     */
    public function sortByBeginHDate(QueryBuilder $qb,string $order){
        return $qb->orderBy('o.beginDateMinIndex',$order);
    }

    /**
     * @param QueryBuilder $qb
     * @param HDate|null $hDate
     * @param $options
     * @return QueryBuilder
     */
    public function filterByEndHDate(QueryBuilder $qb,?HDate $hDate,$options){
        if($hDate === null) return $qb;
        return $qb->andWhere('(o.beginDateType IS NULL OR o.beginDateMinIndex <= :endDateMaxIndex)')
            ->setParameter('endDateMaxIndex', DateHelper::dateToIndex($hDate->getEndDate()));
    }

    /**
     * @param QueryBuilder $qb
     * @param string $order
     * @return QueryBuilder
     */
    public function sortByEndHDate(QueryBuilder $qb,string $order){
        return $qb->orderBy('o.endDateMaxIndex',$order);
    }

    /**
     * @param QueryBuilder $qb
     * @param int|null $ownerId
     * @param $options
     * @return QueryBuilder
     */
    public function filterByOwnerId(QueryBuilder $qb,$ownerId,$options){
        if($ownerId === null) return $qb;
        return $qb->andWhere('(o.ownerUser = :ownerId)')
            ->setParameter('ownerId', $ownerId);
    }

    /**
     * @param QueryBuilder $qb
     * @param string $order
     * @return QueryBuilder
     */
    public function sortByEditionDate(QueryBuilder $qb,string $order){
        return $qb->orderBy('o.editionDate',$order);
    }

    /**
     * @param QueryBuilder $qb
     * @param string $order
     * @return QueryBuilder
     */
    public function sortByFirstPublishedDate(QueryBuilder $qb,string $order){
        return $qb->orderBy('o.firstPublishedDate',$order);
    }

    /**
     * @param QueryBuilder $qb
     * @param string $order
     * @return QueryBuilder
     */
    public function sortByFirstRankLinksCount(QueryBuilder $qb,string $order){
        return $qb->orderBy('o.firstRankLinksCount',$order);
    }
}
