<?php

namespace App\Repository;

use App\Entity\ArticleLink;
use Doctrine\ORM\QueryBuilder;

/**
 * articleHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param QueryBuilder $qb
     * @param int $articleId
     * @param int|null $limit
     * @return QueryBuilder
     */
    public function filterByArticle_id(QueryBuilder $qb,int $articleId,?int $limit){
        return $qb
            ->join('o.article','a')
            ->where('a.id = :articleId')
            ->setParameter('articleId',$articleId);
    }
    
    
    
}
