<?php

namespace App\Repository;
use Doctrine\ORM\QueryBuilder;

/**
 * PopTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PopTypeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function getFindAllQB()
    {
        $qb = $this->createQueryBuilder('o')
        ->select('o')
        ->orderBy('o.label','ASC');
        return $qb;
    }

    /**
     * @return array
     */
    public function findAll()
    {
        return $this->getFindAllQB()->getQuery()->getResult();
    }




}
