<?php

namespace App\Repository;

/**
 * ResourceFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceFileRepository extends \Doctrine\ORM\EntityRepository
{
}
