<?php

namespace App\Repository;

/**
 * ResourceVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceVersionRepository extends \Doctrine\ORM\EntityRepository
{
}
