<?php

namespace App\Repository;

/**
 * GeographyResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceGeometryRepository extends \Doctrine\ORM\EntityRepository
{
}
