/*! Copyright (c) 2011 Piotr Rochala (http://rocha.la)
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 *
 * Version: 1.3.8
 *
 */
(function(e){e.fn.extend({slimScroll:function(s){var i=e.extend({width:'auto',height:'250px',size:'7px',color:'#000',position:'right',distance:'1px',start:'top',opacity:.4,alwaysVisible:!1,disableFadeOut:!1,railVisible:!1,railColor:'#333',railOpacity:.2,railDraggable:!0,railClass:'slimScrollRail',barClass:'slimScrollBar',wrapperClass:'slimScrollDiv',allowPageScroll:!1,wheelStep:20,touchScrollStep:200,borderRadius:'7px',railBorderRadius:'7px'},s);this.each(function(){function w(t){if(p){t=t||window.event;var s=0;t.wheelDelta&&(s=-t.wheelDelta/120);t.detail&&(s=t.detail/3);e(t.target||t.srcTarget||t.srcElement).closest('.'+i.wrapperClass).is(o.parent())&&c(s,!0);t.preventDefault&&!h&&t.preventDefault();h||(t.returnValue=!1)}};function c(e,t,r){h=!1;var s=o.outerHeight()-a.outerHeight();t&&(t=parseInt(a.css('top'))+e*parseInt(i.wheelStep)/100*a.outerHeight(),t=Math.min(Math.max(t,0),s),t=0<e?Math.ceil(t):Math.floor(t),a.css({top:t+'px'}));n=parseInt(a.css('top'))/(o.outerHeight()-a.outerHeight());t=n*(o[0].scrollHeight-o.outerHeight());r&&(t=e,e=t/o[0].scrollHeight*o.outerHeight(),e=Math.min(Math.max(e,0),s),a.css({top:e+'px'}));o.scrollTop(t);o.trigger('slimscrolling',~~t);y();d()};function m(){g=Math.max(o.outerHeight()/o[0].scrollHeight*o.outerHeight(),30);a.css({height:g+'px'});var e=g==o.outerHeight()?'none':'block';a.css({display:e})};function y(){m();clearTimeout(C);n==~~n?(h=i.allowPageScroll,H!=n&&o.trigger('slimscroll',0==~~n?'top':'bottom')):h=!1;H=n;g>=o.outerHeight()?h=!0:(a.stop(!0,!0).fadeIn('fast'),i.railVisible&&l.stop(!0,!0).fadeIn('fast'))};function d(){i.alwaysVisible||(C=setTimeout(function(){i.disableFadeOut&&p||f||b||(a.fadeOut('slow'),l.fadeOut('slow'))},1E3))};var p,f,b,C,v,g,n,H,h=!1,o=e(this);if(o.parent().hasClass(i.wrapperClass)){var u=o.scrollTop(),a=o.siblings('.'+i.barClass),l=o.siblings('.'+i.railClass);m();if(e.isPlainObject(s)){if('height'in s&&'auto'==s.height){o.parent().css('height','auto');o.css('height','auto');var r=o.parent().parent().height();o.parent().css('height',r);o.css('height',r)}
else'height'in s&&(r=s.height,o.parent().css('height',r),o.css('height',r));if('scrollTo'in s)u=parseInt(i.scrollTo);else if('scrollBy'in s)u+=parseInt(i.scrollBy);else if('destroy'in s){a.remove();l.remove();o.unwrap();return};c(u,!1,!0)}}
else if(!(e.isPlainObject(s)&&'destroy'in s)){i.height='auto'==i.height?o.parent().height():i.height;u=e('<div></div>').addClass(i.wrapperClass).css({position:'relative',overflow:'hidden',width:i.width,height:i.height});o.css({overflow:'hidden',width:i.width,height:i.height});var l=e('<div></div>').addClass(i.railClass).css({width:i.size,height:'100%',position:'absolute',top:0,display:i.alwaysVisible&&i.railVisible?'block':'none','border-radius':i.railBorderRadius,background:i.railColor,opacity:i.railOpacity,zIndex:90}),a=e('<div></div>').addClass(i.barClass).css({background:i.color,width:i.size,position:'absolute',top:0,opacity:i.opacity,display:i.alwaysVisible?'block':'none','border-radius':i.borderRadius,BorderRadius:i.borderRadius,MozBorderRadius:i.borderRadius,WebkitBorderRadius:i.borderRadius,zIndex:99}),r='right'==i.position?{right:i.distance}:{left:i.distance};l.css(r);a.css(r);o.wrap(u);o.parent().append(a);o.parent().append(l);i.railDraggable&&a.bind('mousedown',function(i){var s=e(document);b=!0;t=parseFloat(a.css('top'));pageY=i.pageY;s.bind('mousemove.slimscroll',function(e){currTop=t+e.pageY-pageY;a.css('top',currTop);c(0,a.position().top,!1)});s.bind('mouseup.slimscroll',function(e){b=!1;d();s.unbind('.slimscroll')});return!1}).bind('selectstart.slimscroll',function(e){e.stopPropagation();e.preventDefault();return!1});l.hover(function(){y()},function(){d()});a.hover(function(){f=!0},function(){f=!1});o.hover(function(){p=!0;y();d()},function(){p=!1;d()});o.bind('touchstart',function(e,t){e.originalEvent.touches.length&&(v=e.originalEvent.touches[0].pageY)});o.bind('touchmove',function(e){h||e.originalEvent.preventDefault();e.originalEvent.touches.length&&(c((v-e.originalEvent.touches[0].pageY)/i.touchScrollStep,!0),v=e.originalEvent.touches[0].pageY)});m();'bottom'===i.start?(a.css({top:o.outerHeight()-a.outerHeight()}),c(0,!0)):'top'!==i.start&&(c(e(i.start).position().top,null,!0),i.alwaysVisible||a.hide());window.addEventListener?(this.addEventListener('DOMMouseScroll',w,!1),this.addEventListener('mousewheel',w,!1)):document.attachEvent('onmousewheel',w)}});return this}});e.fn.extend({slimscroll:e.fn.slimScroll})})(jQuery);